package shield

import (
	"crypto/rand"
	"crypto/sha512"
	"encoding/hex"

	"golang.org/x/crypto/pbkdf2"
)

// MaxLength indicates the maximum length that a password can have.
const MaxLength = 4096

type Error string

func (e Error) Error() string { return string(e) }

const ErrPasswordTooLong = Error("password too long")

// Shield is a struct that contains basic configuration variables used to
// encrypt and check strings.
//     iterations: is the number of iterations to run PBKDF2.
//     maxLength: indicates the maximum length that a password can have.
//     saltLength: is the length of the salt generated by GenerateSalt.
type Shield struct {
	iterations int
	maxLength  int
	saltLength int
}

// Default returns an instance of Shield initialized with default values for
// each of its variables:
//     iterations: 5000
//     maxLength: 4096
//     saltLength: 32
func Default() Shield {
	return Shield{
		iterations: 5000,
		maxLength:  4096,
		saltLength: 32}
}

// Check returns true if the supplied password matches the password+salt of encrypted.
func (s Shield) Check(password, encrypted []byte) bool {
	hash := encrypted[0:128]
	salt := encrypted[128:]

	return s.digest(password, salt) == string(hash)
}

func (s Shield) digest(password, salt []byte) string {
	dig := pbkdf2.Key(password, salt, s.iterations, sha512.Size, sha512.New)

	return hex.EncodeToString(dig)
}

// Encrypt will return a string with a salt-encrypted version of
// password. This encrypted password is self contained, in the sense
// that there's no need to store the encrypted password and salt
// separatedly, as it will have everything in the returned string.
func (s Shield) Encrypt(password, salt []byte) (string, error) {
	if len(password) > s.maxLength {
		return "", ErrPasswordTooLong
	}
	return s.digest(password, salt) + string(salt), nil
}

// GenerateSalt returns a new salt of SaltLength length filled with
// random bytes.
func (s Shield) GenerateSalt() ([]byte, error) {
	salt := make([]byte, s.saltLength)
	_, err := rand.Read(salt)
	return salt, err
}
